config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :stands
  resources :vendors
  resources :dashboard, only: [ :index ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/vendor.rb
class Vendor < ApplicationRecord
    has_one :stand, dependent: :destroy

    validates :name, presence: true
    validates :contact, presence: true
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :phone, presence: true, format: { with: /\A\+?\d{10,15}\z/, message: I18n.t("validator.phone") }
    validates :address, presence: true

    has_paper_trail

    VISIT_DAYS = [ "saturday", "sunday", "both" ]

    def last_changes_from
      last_version = if stand.present?
       last_version_of_vendor_and_stand
      else
        versions.last
      end

      User.find(last_version.whodunnit).email_address if last_version.present? && last_version.whodunnit.present?
    end

    private def last_version_of_vendor_and_stand
      last_stand_version = stand.versions.last
      last_vendor_version = versions.last

      last_stand_version.created_at > last_vendor_version.created_at ? last_stand_version : last_vendor_version
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: %i[ show edit update destroy ]

  # GET /vendors or /vendors.json
  def index
    if params[:column].present?
      @vendors = Vendor.order("#{params[:column]} #{params[:direction]}")
    else
      @vendors = Vendor.all
    end
    @vendors = @vendors.where("name LIKE :q OR contact LIKE :q", q: "%#{params[:name]}%") if params[:name].present?
  end

  # GET /vendors/1 or /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors or /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to new_stand_path(vendor_id: @vendor.id), notice: I18n.t("vendor.created") }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1 or /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: I18n.t("vendor.updated") }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1 or /vendors/1.json
  def destroy
    @vendor.destroy!

    respond_to do |format|
      format.html { redirect_to vendors_path, status: :see_other, notice: I18n.t("vendor.deleted") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def vendor_params
      params.expect(vendor: [ :name, :legalform, :contact, :address, :phone, :email, :taxnumber, :taxoffice, :last_visit, :visit_day ])
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
  def sort_link(column:, lable:)
    direction = column == params[:column] ? next_direction : "asc"
    link_to(lable, vendors_path(column: column, direction: direction), data: { turbo_action: "replace" })
  end

  def next_direction
    params[:direction] == "asc" ? "desc" : "asc"
  end

  def sort_indicator
    tag.span(class: "sort sort-#{params[:direction]}")
  end

  def show_sort_indicator_for(column)
    sort_indicator if params[:column] == column
  end
end

app/views/vendors/_form.html.erb
<%= simple_form_for vendor, html: { class: 'form-horizontal' } do |form| %>
  <% if vendor.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% vendor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="m-4">
    <%= form.input :name, input_html: { class: 'form-control' } %>
    <%= form.input :legalform, placeholder: I18n.t("vendor.form.placeholder.legalform"), input_html: { class: 'form-control' } %>
    <%= form.input :contact, input_html: { class: 'form-control' } %>
    <%= form.input :address, placeholder: I18n.t("vendor.form.placeholder.address"), input_html: { class: 'form-control' } %>
    <%= form.input :phone, input_html: { class: 'form-control' } %>
    <%= form.input :email, input_html: { class: 'form-control' } %>
    <%= form.input :taxnumber, input_html: { class: 'form-control' } %>
    <%= form.input :taxoffice, input_html: { class: 'form-control' } %>
    <%= form.input :last_visit, as: :string, placeholder: I18n.t("vendor.form.placeholder.last_visit"), input_html: { class: 'form-control' } %>
    <%= form.input :visit_day, as: :select, collection: Vendor::VISIT_DAYS.map { |day| t("vendor.visit_days.#{day}") }, include_blank: "Bitte auswählen", input_html: { class: 'form-control' } %>
    <div class="form-group">
      <%= form.button :submit, "Speichern", class: "btn btn-primary mt-3" %>
    </div>
  </div>
<% end %>

app/views/vendors/_vendor.html.erb
    <tr>
      <td><%= vendor.id %></td>
      <td><%= link_to vendor.name, vendor %></td>
      <td><%= vendor.contact %></td>
      <td><%= vendor.phone %></td>
      <td><%= vendor.email %></td>
      <% if vendor.stand.present? %>
        <td><%= link_to "Stand", vendor.stand %></td>
      <% else %>
        <td></td>
      <% end %>    
      <td><%= vendor.visit_day %></td>
      <td><%= vendor.last_changes_from %></td>
      <td>
        <%= button_to vendor, method: :delete, class: "btn btn-danger", form: { data: { turbo_confirm: "SURE about that?" } } do %>
          <i class="bi bi-trash"></i>
        <% end %>
      </td>
    </tr>

app/views/vendors/_vendor_detail.html.erb
<div class="card m-3">
  <div class="card-body">
    <h2 class="card-title">Angaben zum Standinhabenden
      <span>
        <a href="<%= edit_vendor_path(@vendor) %>" title="Bearbeiten">
        <i class="bi bi-pencil"></i>
      </a>
    </span></h2>
    <div class="row">
      <div class="col-md-6">
        <h4><strong>Name des Betreibenden/Ausstellenden:</strong> <%= vendor.name %></h4>
        <p><strong>Rechtsform:</strong> <%= vendor.legalform %></p>
        <p><strong>Ansprechpartner*in:</strong> <%= vendor.contact %></p>
        <p><strong>Adresse:</strong> <%= vendor.address %></p>
      </div>
      <div class="col-md-6">
        <p><strong>Steuernummer:</strong> <%= vendor.taxnumber %></p>
        <p><strong>Zuständiges Finanzamt:</strong> <%= vendor.taxoffice %></p>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-md-6">
        <p><strong>Telefon/Mobilfunknummer:</strong> <%= vendor.phone %></p>
        <p><strong>E-Mail-Adresse:</strong> <%= vendor.email %></p>
      </div>
      <div class="col-md-6">
        <p><strong>Letzter Besuch:</strong> <%= vendor.last_visit %></p>
        <p><strong>Besuchstag:</strong> <%= vendor.visit_day %></p>
      </div>
    </div>
  </div>
</div>

app/views/vendors/edit.html.erb
<% content_for :title, I18n.t("vendor.header.edit") %>
      <span>
        <a href="<%= vendors_path %>" title="Zurück">
        <i class="bi bi-arrow-left-circle"></i>
      </a>
    </span>
<div class="container mt-4">

<h1><%=I18n.t("vendor.header.edit") %></h1>

<%= render "form", vendor: @vendor %>

<br>

<div>
  <%= link_to I18n.t("vendor.actions.show"), @vendor %> |
  <%= link_to "Zurück zur Händlerübersicht", vendors_path %>
</div>
</div>

app/views/vendors/index.html.erb
<% content_for :title, "Händler" %>

<div class="container mt-4">

<div id="vendors">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Angemeldete Händler für den Sonntagsmarkt</h2>
      <p class="card-text">Hier finden Sie alle Händler, die an der Veranstaltung teilnehmen.</p>
      <%= link_to "Neuen Händler anlegen", new_vendor_path, class: "btn btn-primary btn-lg m-3 text-decoration-none text-secondary" %>
      <div class="row mb-3">
        <div class="col d-flex justify-content-end">
          <%= form_with url: vendors_path, method: :get, data: { controller: "search-form", search_form_target: "form", turbo_frame: "vendors" }, class: "d-flex align-items-end" do |form| %>
            <div class="me-2">
              <%= form.label :name, "Suche", class: "form-label" %>
              <%= form.text_field :name, placeholder: I18n.t("vendor.actions.search"), value: params[:name], class: "form-control", data: { action: "input->search-form#search", search_form_target: "input" } %>
            </div>
            <%= form.submit "Suchen", class: "btn btn-primary mb-1" %>
          <% end %>
        </div>
      </div>
      <div class="overflow-scroll-sm">
        <table class="table sort-link">
          <thead>
            <tr>
              <th>
                <%= sort_link(column: "id", lable: Vendor.human_attribute_name("id")) %>
                <%= show_sort_indicator_for("id")%>
              </th>
              <th>
                <%= sort_link(column: "name", lable: Vendor.human_attribute_name("name")) %>
                <%= show_sort_indicator_for("name")%>
              </th>
              <th><%= Vendor.human_attribute_name("contact")%></th>
              <th><%= Vendor.human_attribute_name("phone")%></th>
              <th><%= Vendor.human_attribute_name("email")%></th>
              <th>Stand</th>
              <th><%= sort_link(column: "visit_day", lable: Vendor.human_attribute_name("visit_day")) %></th>
              <th>zuletzt bearbeitet</th>
          </thead>
          <%= turbo_frame_tag "vendors" do %>
            <tbody class="table-group-divider">
              <% @vendors.each do |vendor| %>
                <%= render vendor %>
              <% end %>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/vendors/new.html.erb
<% content_for :title, "Händler Hinzufügen" %>

<div class="container mt-4">
  <h1 class="new-headlines"><%= I18n.t("vendor.header.new")%></h1>

  <%= render "form", vendor: @vendor %>

  <br>

  <div>
    <%= link_to "Zurück zur Händlerübersicht", vendors_path %>
  </div>
</div>

app/views/vendors/show.html.erb
<%= render 'vendors/vendor_detail', vendor: @vendor %>
<hr>
<%= render 'stands/stand', stand: @vendor.stand %>

<div>
  <%= link_to "Zurück zur Händlerübersicht", vendors_path %>

  <%= button_to I18n.t("vendor.actions.delete"), @vendor, method: :delete, class:"btn btn-primary" %>
</div>