config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :stands
  resources :vendors
  resources :dashboard, only: [ :index ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/stand.rb
class Stand < ApplicationRecord
  belongs_to :vendor

  validates :height, presence: true, numericality: { greater_than: 0 }
  validates :width, presence: true, numericality: { greater_than: 0 }
  validates :depth, presence: true, numericality: { greater_than: 0 }

  has_paper_trail
end

app/controllers/stands_controller.rb
class StandsController < ApplicationController
  before_action :set_stand, only: %i[ show edit update destroy ]

  # GET /stands or /stands.json
  def index
    @stands = Stand.all
  end

  # GET /stands/1 or /stands/1.json
  def show
  end

  # GET /stands/new
  def new
    @stand = Stand.new(vendor_id: stand_new_params[:vendor_id])
  end

  # GET /stands/1/edit
  def edit
  end

  # POST /stands or /stands.json
  def create
    @stand = Stand.new(stand_params)

    respond_to do |format|
      if @stand.save
        format.html { redirect_to @stand.vendor, notice: I18n.t("stand.created") }
        format.json { render :show, status: :created, location: @stand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stands/1 or /stands/1.json
  def update
    respond_to do |format|
      if @stand.update(stand_params)
        format.html { redirect_to @stand, notice: I18n.t("stand.updated") }
        format.json { render :show, status: :ok, location: @stand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stands/1 or /stands/1.json
  def destroy
    @stand.destroy!

    respond_to do |format|
      format.html { redirect_to stands_path, status: :see_other, notice: I18n.t("stand.destroyed") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stand
      @stand = Stand.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def stand_params
      params.expect(stand: [ :width, :height, :depth, :diameter, :description, :cooler, :table, :selfdriver, :trailer, :power, :specials, :misc, :vendor_id ])
    end

    def stand_new_params
      params.permit(:vendor_id)
    end
end

app/helpers/stands_helper.rb
module StandsHelper
end

app/views/stands/_form.html.erb
<%= simple_form_for stand, html: { class: 'form-horizontal'} do |form| %>
  <% if stand.errors.any? %>
     <div class="alert alert-danger">
      <ul>
        <% stand.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="m-4">
  <%= form.input :width, input_html: {class: 'form-control'}%>
  <%= form.input :height, input_html: {class: 'form-control'}%>
  <%= form.input :depth, input_html: {class: 'form-control'}%>
  <%= form.input :diameter, input_html: {class: 'form-control'}%>
  <%= form.input :description, as: :text, placeholder: I18n.t("stand.form.placeholder.description"), input_html: {class: 'form-control', rows: 5} %>
  <%= form.input :cooler, input_html: {class: 'form-control'}%>
  <%= form.input :table, input_html: {class: 'form-control'}%>
  <%= form.input :selfdriver, input_html: {class: 'form-check-input', style: 'width: 1.5rem; height: 1.5rem'}, label_html: {style: 'margin-left: 1rem'} %>
  <%= form.input :trailer, input_html: {class: 'form-check-input', style: 'width: 1.5rem; height: 1.5rem'}, label_html: {style: 'margin-left: 1rem;'} %>
  <%= form.input :power, input_html: {class: 'form-check-input', style: 'width: 1.5rem; height: 1.5rem'}, label_html: {style: 'margin-left: 1rem;'} %>
  <%= form.input :specials, input_html: {class: 'form-control'}%>
  <%= form.input :misc, input_html: {class: 'form-control'}%>
  <%= form.hidden_field :vendor_id %>

  <div>
    <%= form.button :submit, "Speichern", class: "btn btn-primary mt-3" %>
  </div>
</div>
<% end %>

app/views/stands/_stand.html.erb
<% if stand.present? %>
  <div id="<%= dom_id stand %>" class="card m-3">
    <div class="card-body">
      <h5 class="card-title">Stand Details
        <span>
          <a href="<%= edit_stand_path(stand) %>" title="<%= I18n.t("stand.actions.edit")%>"> 
            <i class="bi bi-pencil"></i>
          </a>
        </span>
      </h5>
      <div class="row">
        <div class="col-md-6">
          <p><strong>Frontmeter:</strong> <%= stand.width %></p>
          <p><strong>Höhe:</strong> <%= stand.height %></p>
          <p><strong>Tiefe:</strong> <%= stand.depth %></p>
          <p><strong>Durchmesser:</strong> <%= stand.diameter %></p>
        </div>
        <div class="col-md-6">
          <p><strong>Beschreibung:</strong> <%= stand.description %></p>
          <p><strong>Kühlwagen:</strong> <%= stand.cooler %></p>
          <p><strong>Tische/Schirme:</strong> <%= stand.table %></p>
          <p><strong>Selbstfahrer:</strong> <%= stand.selfdriver %></p>
        </div>
      </div>
      <div class="row mt-3">
        <div class="col-md-6">
          <p><strong>Anhänger:</strong> <%= stand.trailer %></p>
          <p><strong>Stromanschluss (230 V):</strong> <%= stand.power %></p>
          <p><strong>andere Besonderheiten:</strong> <%= stand.specials %></p>
        </div>
        <div class="col-md-6">
          <p><strong>Sonstiges:</strong> <%= stand.misc %></p>
          <p><strong>Händler:</strong> <%= stand.vendor_id %></p>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="alert alert-warning">
    <p><%=I18n.t("stand.empty")%></p>
  </div>
<% end %>

app/views/stands/edit.html.erb
<% content_for :title, "Editing stand" %>

<div class="container mt-4">
  <h1><%= I18n.t("stand.header.edit")%></h1>

  <%= render "form", stand: @stand %>

  <br>

  <div>
    <%= link_to I18n.t("stand.actions.show"), @stand %> |
    <%= link_to I18n.t("stand.actions.show_all"), stands_path %>
  </div>
</div>

app/views/stands/index.html.erb
<% content_for :title, "Stands" %>

<h1>Stands</h1>

<div id="stands">
  <% @stands.each do |stand| %>
    <%= render stand %>
    <p>
      <%= link_to "Show this stand", stand %>
    </p>
  <% end %>
</div>

<%= link_to "New stand", new_stand_path %>

app/views/stands/new.html.erb
<% content_for :title, "Stand hinzufügen" %>

<div class="container mt-4">
  <h1 class="new-headlines"><%= I18n.t("stand.header.new")%></h1>

  <%= render "form", stand: @stand %>

  <br>
  <div>
    <%= link_to "Back to stands", stands_path %>
  </div>
</div>

app/views/stands/show.html.erb
<%= render @stand %>

<div>
  <%= link_to "Back to stands", stands_path %>

  <%= button_to I18n.t("stand.actions.delete"), @stand, method: :delete, class: "btn btn-primary" %>
</div>