config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :stands
  resources :vendors
  resources :dashboard, only: [ :index ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/views/layouts/_footer.html.erb
<footer class="bg-light py-2 fixed-bottom">
    <ul class="nav justify-content-center">
        <li class="nav-item">
            <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#imprint">
            <%= I18n.t("legal.imprint") %></button>
        </li>
        <li class="nav-item mx-3">
        <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#privacy">
            <%= I18n.t("legal.privacy") %> </button>
        </li>
    </ul>
</footer>

<!-- Modal Impressum-->
<div class="modal fade" id="imprint" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel"><%= I18n.t("legal.imprint") %></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
       <%= render "layouts/imprint" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Understood</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal Datenschutz-->
<div class="modal fade" id="privacy" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel"><%= I18n.t("legal.privacy") %> </h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
       <%= render "layouts/privacy" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Understood</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_imprint.html.erb
<h1>Impressum</h1><p>Angaben gemäß § 5 DDG</p><p>Volksfestverein Malchow e.V.<br> 
<br> 
Bahnhofstr. 5<br> 
17213  Malchow <br> 
</p><p> <strong>Vertreten durch: </strong><br>
Daniela Lemke<br>
</p><p><strong>Haftungsausschluss: </strong><br><br><strong>Haftung für Inhalte</strong><br><br>
Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte können wir jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir gemäß § 7 Abs.1 DDG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 DDG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.<br><br><strong>Haftung für Links</strong><br><br>
Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.<br><br><strong>Urheberrecht</strong><br><br>
Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.<br><br><strong>Datenschutz</strong><br><br>
Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder eMail-Adressen) erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben. <br>
Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich. <br>
Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten durch Dritte zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit ausdrücklich widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.<br>
</p><br> 
Erstellt mit dem <a href="https://impressum-generator.de" rel="dofollow">Impressum-Generator</a> von WebsiteWissen.com, dem Ratgeber für <a href="https://websitewissen.com/website-erstellen" rel="dofollow">Website-Erstellung</a>, <a href="https://websitewissen.com/homepage-baukasten-vergleich" rel="dofollow">Homepage-Baukästen</a> und <a href="https://websitewissen.com/shopsysteme-vergleich" rel="dofollow">Shopsysteme</a>. Rechtstext von der <a href="https://www.kanzlei-hasselbach.de/" rel="dofollow">Kanzlei Hasselbach</a>. 

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <ul class="navbar-nav d-flex flex-row align-items-center list-unstyled">
      <li class="nav-item me-3">
        <img src="<%= asset_path('logo_volksfestverein.png') %>" alt="" width="50" height="50" class="d-inline-block align-text-center">
        </li>
    <li class="nav-item me-3">
        <%= link_to "Sonntagsmarkt", root_path, class: "nav-link custom-text-color" %>
      </li>
      <li class="nav-item me-3">
        <%= link_to "Händler", vendors_path, class: "nav-link custom-text-color" %>
      </li>
    </ul>
    <div class="d-flex">
      <%= button_to "Logout", session_path,  class: "btn btn-primary", method: :delete if authenticated? %>
    </div>
  </div>
</nav>

app/views/layouts/_privacy.html.erb
<h1>DATENSCHUTZHINWEISE</h1><p>GEMÄSS ART. 13 DSGVO</p><p>Volksfestverein Malchow e.V.<br> 
<br> 
Bahnhofstr. 5<br> 
17213  Malchow <br> 
</p>Bei Fragen zum Datenschutz stehen wir Ihnen unter info@volksfestverein.de oder unter der oben angegebenen postalischen Anschrift zur Verfügung.<p> 
</p><p><h3>DATENVERARBEITUNG AUF UNSERER WEBSEITE UND WEITEREN ONLINE-ANGEBOTEN </h3><br>
<p><strong>Logfiles beim Aufruf unserer Webseite</strong></p>
</p>Bei Aufruf unserer Webseite werden zur Analyse von Fehlern und Sicherheitsvorfällen Logfiles erstellt. Diese bleiben nur für einige Tage bis Wochen gespeichert und werden anschließend automatisch gelöscht.
<br>Für das Hosting unserer Webseite verwenden wir Hetzner als externen Dienstleister. Die Speicherung der Logfiles erfolgt dort.
<p></p>
<p><h3>DATENVERARBEITUNG IM RAHMEN UNSERER VEREINSARBEIT</h3></p>
<p>Daten zur Erfassung und Verwaltung von Anmeldung für einen Standplatz auf dem Sonntagsmarkt zum Volksfest in Malchow werden von den jeweiligen Funktionsträger:innen unseres Vereins nur für die ihnen zugeordnete Aufgabenerfüllung verarbeitet. Im Einzelnen bedeutet dies:

Wenn der Verein Händlerdaten benötigt, um seine Aufgaben zu erledigen, darf er auf alle hierfür erforderlichen Händlerdaten zugreifen. Dazu gehört insbesondere zur Verwaltung von Anmeldung für einen Standplatz auf dem Sonntagsmarkt zum Volksfest in Malchow angegebene Daten.
Die aktuellen Händlerdaten werden für die Dauer bis zum Volksfest und darüber hinaus für ein Jahr, bis zum nächsten Volksfest gespeichert.</p>
<p></p>
<p><h3>BETROFFENENRECHTE</h3></p>
<p>Wenn wir personenbezogene Daten von Ihnen verarbeiten, haben Sie folgende Betroffenenrechte:</p>
<p>ein Recht auf Auskunft über die verarbeiteten Daten und auf Kopie,</p>
<p>ein Berichtigungsrecht, wenn wir falsche Daten über Sie verarbeiten,</p>
<p>ein Recht auf Löschung, es sei denn, dass noch Ausnahmen greifen, warum wir die Daten noch speichern, also zum Beispiel Aufbewahrungspflichten oder Verjährungsfristen</p>
<p>ein Recht auf Einschränkung der Verarbeitung,</p>
<p>ein jederzeitiges Recht, Einwilligungen in die Datenverarbeitung zu widerrufen,</p>
<p>ein Widerspruchsrecht gegen eine Verarbeitung im öffentlichen oder bei berechtigtem Interesse,</p>
<p>ein Recht auf Datenübertragbarkeit,</p>
<p>ein Beschwerderecht bei einer Datenschutz-Aufsichtsbehörde, wenn Sie finden, dass wir Ihre Daten nicht ordnungsgemäß verarbeiten. Für unseren Verein ist der Landesbeauftragte für Datenschutz und Informationsfreiheit Mecklenburg-Vorpommern zuständig. Wenn Sie sich in einem anderen Bundesland oder nicht in Deutschland aufhalten, können Sie sich aber auch an die dortige Datenschutzbehörde wenden.</p>
<p></p>
<p>Dieser Text wurde mit dem Generator für Datenschutzhinweise der Stiftung Datenschutz erstellt.</p>
<p></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sonntagsmarkt" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="turbo-refresh-method" content="morph">
    <meta name="turbo-refresh-scroll" content="preserve">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag 'favicon.ico', type: 'image/png' %>
    <% if content_for? :head %>
      <%= turbo_refreshes_with method: :morph, scroll: :preserve %>
      <%= yield :head %>
    <% end %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-bs-theme="light">
    <%= render "layouts/nav" if authenticated?%>

    <% if notice.present? %>
      <p class="alert alert-success" role="alert"><%= notice %></p>
    <% end %>

    <%= yield %>
    
    <%= render "layouts/footer"%>
  </body>
</html>